'use strict';
(() => {
const $=id=>document.getElementById(id);
const chapters=[
 ['rumor','দাওয়াতের কার্ডের রহস্য','চার টুকরো কার্ড খুঁজে সঠিক ঘরে বসান।'],
 ['jealous','দর্জির দোকানে সারপ্রাইজ','নমুনার সঙ্গে শাড়ির রং ও পাড় মিলিয়ে সেলাই করুন।'],
 ['phone','ফোন থাকুক দূরে','ফোন সরিয়ে রাখুন, সময়মতো চাওয়া জিনিস পৌঁছে দিন।'],
 ['market','ধনেপাতার দৌড়','বাজারে তালিকার চারটি জিনিস কুড়িয়ে বাড়ি ফিরুন।'],
 ['birthday','কেক বাঁচাও, চমক সাজাও','প্লেট সরিয়ে তিনটি কেক ধরুন, তারপর জন্মদিন সাজান।'],
 ['chores','বাসন ঘষি, চা বানাই','ময়লার ওপর আঙুল ঘষুন; তারপর ঠিক সময়ে চিনির মিটার থামান।']
].map(([key,name,story])=>({key,name,story,line:story,role:'husband',type:'mend',shots:0}));
let current,hooks,board,status,prompt,drag=null;
const goods=['🥬','🍅','🐟','🌿'],colors=['#e65b83','#4c9bc6','#e4b440'];
function el(tag,cls,text){const e=document.createElement(tag);e.className=cls||'';if(text!==undefined)e.textContent=text;return e;}
function active(){return current&&current.g.state==='mending';}
function button(label,x,y,fn,cls=''){const b=el('button','toy '+cls,label);b.type='button';b.style.left=x+'%';b.style.top=y+'%';b.onclick=()=>{if(active())fn();};board.appendChild(b);return b;}
function note(text){current.g.mending.message=text;status.textContent=text;}
function score(n=100){current.g.score+=n;hooks.tone(560,.08);hooks.hud();}
function fail(text){const m=current.g.mending;m.mistakes++;m.anger=Math.min(100,m.anger+8);current.g.scratch=1;note(text);hooks.tone(160,.08);meter();}
function meter(){const m=current.g.mending;$('anger').value=m.anger;$('anger-text').textContent='অভিমান '+Math.round(m.anger)+'%';}
function progress(){const m=current.g.mending;m.actions++;m.anger=Math.max(5,90-m.actions*16);score();meter();}
function win(){const {g}=current,m=g.mending;if(!active())return;m.anger=0;meter();g.shotCount=m.mistakes;g.score+=Math.max(200,1000-m.mistakes*100);note('সব কাজ শেষ! এবার একসঙ্গে হাসির সময় ♡');board.querySelectorAll('button').forEach(b=>b.disabled=true);hooks.win();}
function mount(){board.replaceChildren();drag=null;board.onkeydown=null;}
function setPrompt(text){prompt.textContent=text;}
function start(g,d,h){hooks=h;current={g,d};g.state='mending';g.mending={anger:90,stage:0,actions:0,mistakes:0,time:0,left:40,selected:null,placed:[],collected:[],scrubs:0,sugar:0,message:d.story,x:50,cakeX:50,cakeY:0,caught:0,phoneAway:false,request:0,deadline:6,mx:2,my:3};
 $('mend-actions').replaceChildren();prompt=$('mend-prompt');status=$('mend-progress');board=el('div','mini-board');board.id='mini-board';board.setAttribute('aria-label',d.name);$('mend-actions').appendChild(board);
 board.onpointermove=e=>{if(!active())return;const r=board.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*100,y=(e.clientY-r.top)/r.height*100;const m=g.mending;if(d.key==='birthday'&&m.stage===0){m.x=Math.max(8,Math.min(92,x));updateCatch();}if(d.key==='chores'&&m.stage===0&&e.buttons)scrub(x,y);if(drag){drag.b.style.left=x+'%';drag.b.style.top=y+'%';}};
 board.onpointerup=e=>{if(!drag||!active())return;const r=board.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*100,y=(e.clientY-r.top)/r.height*100,item=drag;drag=null;place(item.id,x,y);};
 board.onpointercancel=()=>{drag=null;draw();};draw();note(d.story);meter();}
function draggable(b,id){b.onpointerdown=e=>{if(!active())return;current.g.mending.selected=id;drag={b,id};b.setPointerCapture(e.pointerId);};}
function place(id,x,y){const {d,g}=current,m=g.mending;if(d.key==='rumor'){const i=Number(id),tx=22+i%2*24,ty=28+Math.floor(i/2)*22;if(Math.abs(x-tx)<12&&Math.abs(y-ty)<11&&!m.placed.includes(i)){m.placed.push(i);progress();if(m.placed.length===4){draw();win();note('দাওয়াত: বর-বউ, মা-বোন—সবাই মেলায়!');return;}}else if(y<62)fail('এই টুকরোটা অন্য ঘরে বসবে!');}
 if(d.key==='birthday'&&m.stage===1){const i=Number(id),tx=35+i*15;if(Math.abs(x-tx)<10&&Math.abs(y-43)<16&&!m.placed.includes(i)){m.placed.push(i);progress();if(m.placed.length===3){m.stage=2;m.placed=[];}}}draw();}
function draw(){if(!current)return;mount();const {d,g}=current,m=g.mending;
 if(d.key==='rumor'){setPrompt('টুকরো টেনে মিলিয়ে বসান · অথবা টুকরো ও ঘরে ট্যাপ করুন');['বর-বউ','মা-বোন','মেলার','দাওয়াত!'].forEach((word,i)=>{const x=22+i%2*24,y=28+Math.floor(i/2)*22;button(m.placed.includes(i)?word:String(i+1),x,y,()=>{if(m.selected!==null)place(m.selected,x,y);},'card-slot');if(!m.placed.includes(i)){const b=button((i+1)+' · '+word,16+i*22,80,()=>{m.selected=i;note((i+1)+' নম্বর ঘরে বসান');},'card-piece');draggable(b,i);}});board.appendChild(el('div','board-decoration','🌳 🏡 🐓'));}
 if(d.key==='jealous'){setPrompt('নমুনা: নীল শাড়ি + ফুলের পাড় · দুটো মিলিয়ে সেলাই');board.appendChild(el('div','sari sample','✿ ✿ ✿'));const sari=el('div','sari creation',m.pattern===1?'✿ ✿ ✿':m.pattern===2?'◆ ◆ ◆':'● ● ●');sari.style.background=colors[m.color??0];board.appendChild(sari);colors.forEach((c,i)=>{const b=button(['গোলাপি','নীল','হলুদ'][i],20+i*30,64,()=>{m.color=i;draw();},'swatch');b.style.background=c;});['● ফোঁটা','✿ ফুল','◆ বরফি'].forEach((s,i)=>button(s,20+i*30,81,()=>{m.pattern=i;draw();}));button('🪡 সেলাই',80,29,()=>{if(m.color===1&&m.pattern===1){progress();win();}else fail('নমুনার রং আর পাড় আবার মিলিয়ে দেখুন!');});}
 if(d.key==='phone'){setPrompt('চাওয়া জিনিসে ট্যাপ করুন · ফোনে হাত দিলেই সময় নষ্ট!');button(m.phoneAway?'📱 সরানো আছে':'📱 ফোন সরান',78,29,()=>{if(!m.phoneAway){m.phoneAway=true;m.deadline=6;note('ফোন দূরে। এবার জিনিস পৌঁছে দিন!');draw();}else{m.phoneAway=false;fail('তোমার সংসার কি ফোনের সাথে?');draw();}},'phone-toy');const ask=el('div','request');ask.id='mini-request';board.appendChild(ask);['☕','💧','🪭'].forEach((v,i)=>button(v,22+i*28,76,()=>{if(!m.phoneAway){fail('আগে ফোনটা সরিয়ে রাখুন!');return;}if(i===m.request){progress();m.request=(m.request+1)%3;m.deadline=6;if(m.actions===6){win();return;}note('ঠিক সময়ে পৌঁছেছে!');updatePhone();}else{m.deadline=Math.max(1,m.deadline-1);fail('অন্য জিনিসটা চেয়েছে!');}},'object-toy'));updatePhone();}
 if(d.key==='market'){setPrompt('৪০ সেকেন্ডে বাজার করুন · তীর বা পাশের ঘরে ট্যাপ');for(let y=0;y<4;y++)for(let x=0;x<5;x++){const b=button('',10+x*20,17+y*21,()=>moveMarket(x,y),'market-cell');b.setAttribute('aria-label','পথ '+x+','+y);const i=[[0,0],[4,0],[4,2],[1,1]].findIndex(p=>p[0]===x&&p[1]===y);b.textContent=x===m.mx&&y===m.my?'🧑':i>=0&&!m.collected.includes(i)?goods[i]:x===2&&y===3?'🏠':(x===2&&y===1)||(x===2&&y===2)?'🧺':'·';}board.tabIndex=0;board.onkeydown=e=>{const v={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(v){e.preventDefault();moveMarket(m.mx+v[0],m.my+v[1]);}};updateMarket();}
 if(d.key==='birthday'){if(m.stage===0){setPrompt('প্লেট সরিয়ে ৩টি কেক ধরুন · আঙুল / ← →');const cake=el('div','falling-cake','🎂');cake.id='falling-cake';board.appendChild(cake);const plate=el('div','catch-plate','🍽️');plate.id='catch-plate';board.appendChild(plate);button('←',12,88,()=>{m.x=Math.max(8,m.x-12);updateCatch();});button('→',88,88,()=>{m.x=Math.min(92,m.x+12);updateCatch();});board.tabIndex=0;board.onkeydown=e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();m.x=Math.max(8,Math.min(92,m.x+(e.key==='ArrowLeft'?-6:6)));updateCatch();}};updateCatch();}else if(m.stage===1){setPrompt('৩টি মোমবাতি টেনে কেকে বসান · ট্যাপ করেও বসানো যায়');board.appendChild(el('div','birthday-cake','🎂'));for(let i=0;i<3;i++){button(m.placed.includes(i)?'🕯️':String(i+1),35+i*15,43,()=>{if(m.selected!==null)place(m.selected,35+i*15,43);},'candle-slot');if(!m.placed.includes(i)){const b=button('🕯️ '+(i+1),25+i*25,82,()=>{m.selected=i;note('একই নম্বরের ঘরে বসান');});draggable(b,i);}}}else{setPrompt('উড়ন্ত ৫টি বেলুন ফাটিয়ে সারপ্রাইজ খুলুন');for(let i=0;i<5;i++)if(!m.placed.includes(i)){const b=button('🎈',14+i*18,50,()=>{m.placed.push(i);progress();if(m.placed.length===5){win();return;}draw();},'floating-balloon');b.setAttribute('aria-label','বেলুন '+(i+1));b.style.animationDelay=(-i*.7)+'s';}}}
 if(d.key==='chores'){if(m.stage===0){setPrompt('ময়লার ওপর আঙুল ঘষুন · কিবোর্ডে ময়লায় Space');board.appendChild(el('div','dish',''));for(let i=0;i<12;i++)if(!m.placed.includes(i)){button('●',32+(i%4)*12,29+Math.floor(i/4)*19,()=>clean(i),'dirt dirt-'+i);}note('পরিষ্কার: '+m.placed.length+' / ১২');}else{setPrompt('চলন্ত চামচ সবুজ অংশে এলে থামান · ২ বার');const track=el('div','sugar-track');track.appendChild(el('span','sweet-zone'));const marker=el('span','sugar-marker','🥄');marker.id='sugar-marker';track.appendChild(marker);board.appendChild(track);button('☕ চিনি থামান',50,76,()=>{if(m.sugarPos>=40&&m.sugarPos<=60){m.sugar++;progress();note('ঠিক মাপ! '+m.sugar+' / ২ চামচ');if(m.sugar===2)win();}else{fail('চিনি মাপ মিলল না! নতুন কাপ, আবার চেষ্টা।');m.sugar=0;}});}}
 board.classList.toggle('market-board',d.key==='market');}
function clean(i){const m=current.g.mending;if(!active()||m.placed.includes(i))return;m.placed.push(i);m.scrubs++;score(30);const b=board.querySelector('.dirt-'+i);if(b)b.remove();m.anger=Math.max(15,90-m.placed.length*5);meter();note('পরিষ্কার: '+m.placed.length+' / ১২');if(m.placed.length===12){m.stage=1;draw();}}
function scrub(x,y){for(let i=0;i<12;i++)if(Math.abs(x-(32+i%4*12))<8&&Math.abs(y-(29+Math.floor(i/4)*19))<10){clean(i);if(current.g.mending.stage!==0)break;}}
function moveMarket(x,y){const m=current.g.mending;if(!active()||x<0||x>4||y<0||y>3||Math.abs(x-m.mx)+Math.abs(y-m.my)!==1||(x===2&&(y===1||y===2)))return;m.mx=x;m.my=y;[[0,0],[4,0],[4,2],[1,1]].forEach((p,i)=>{if(x===p[0]&&y===p[1]&&!m.collected.includes(i)){m.collected.push(i);progress();}});if(x===2&&y===3&&m.collected.length===4){win();return;}draw();board.focus();}
function updateMarket(){const m=current.g.mending;note('সময় '+Math.ceil(m.left)+' · তালিকা '+goods.map((s,i)=>m.collected.includes(i)?'✓'+s:s).join(' '));}
function updatePhone(){const m=current.g.mending,r=$('mini-request');if(r)r.textContent=['☕ চা','💧 পানি','🪭 পাখা'][m.request]+' চাই! '+Math.ceil(m.deadline)+' সেকেন্ড · '+m.actions+'/৬';}
function updateCatch(){const m=current.g.mending;if($('catch-plate'))$('catch-plate').style.left=m.x+'%';if($('falling-cake')){$('falling-cake').style.left=m.cakeX+'%';$('falling-cake').style.top=m.cakeY+'%';}}
function tick(g,d,dt){if(!active())return;const m=g.mending;m.time+=dt;if(d.key==='market'){m.left-=dt;if(m.left<=0){m.left=40;m.collected=[];m.mx=2;m.my=3;m.actions=0;g.score=0;fail('সময় শেষ! নতুন তালিকা নিয়ে আবার দৌড়ান।');hooks.hud();draw();}updateMarket();}if(d.key==='phone'){m.deadline-=dt;if(m.deadline<=0){m.deadline=6;fail('দেরি হয়ে গেল! এবার তাড়াতাড়ি দিন।');}updatePhone();const b=board.querySelector('.phone-toy');if(b)b.classList.toggle('buzz',Math.floor(m.time)%4===0);}
 if(d.key==='birthday'&&m.stage===0){m.cakeY+=dt*23;if(m.cakeY>=77){if(Math.abs(m.x-m.cakeX)<15){m.caught++;progress();note('কেক ধরেছেন '+m.caught+' / ৩');}else fail('কেক পড়ে গেল! প্লেটটা নিচে আনুন।');m.cakeY=0;m.cakeX=[25,75,50,35,65][Math.floor(m.time)%5];if(m.caught===3){m.stage=1;m.placed=[];draw();return;}}updateCatch();}
 if(d.key==='chores'&&m.stage===1){m.sugarPos=50+46*Math.sin(m.time*2.2);if($('sugar-marker'))$('sugar-marker').style.left=m.sugarPos+'%';}}
function render(){if(current)meter();}
window.AngryBouMend={chapters,start,tick,render};
})();
