'use strict';
(() => {
const $=id=>document.getElementById(id);
const chapters=[
 {key:'rumor',name:'মা-বোনের কথায় ভুল বোঝাবুঝি',story:'মা-বোন বেড়াতে এসে শোনা কথা বলেছে। আগে বউয়ের কথা শুনুন, তারপর দুজন মিলে আসল ঘটনা জানুন।',line:'বউ: “মা আর বোন তো অন্য কথা বলল! আসল ঘটনা কী?”',steps:[{prompt:'মা: “শুনলাম জামাই নাকি মেলায় একাই যাবে!” বোন: “আমিও শুনছি!”',choices:[['listen','আগে তোমার কথাটা শুনি'],['blame','সব দোষ তোমার পরিবারের!'],['ignore','বাদ দাও, কিছুই হয়নি']],correct:'listen',reply:'বউ: “শুনে আমার খারাপ লেগেছে। আগে আমাকে বললে পারতে।”'},{prompt:'আসল পরিকল্পনা কী ছিল?',choices:[['explain','টিকিট আনতে গিয়েছিলাম; দুজনেই যাব'],['shout','তোমরা কিছুই বোঝো না!'],['gift','কথা বাদ, চুড়ি নাও']],correct:'explain',reply:'বর: “আমি দুজনের টিকিট আনতেই গিয়েছিলাম। বলতে দেরি হয়েছে।”'},{prompt:'এবার মা-বোনও জানতে চাইছে।',choices:[['tea','সবাই বসে চা খাই, ভুলটা মিটাই'],['argue','আবার তর্ক শুরু করি']],correct:'tea',reply:'মা: “ওমা! অর্ধেক কথা শুনে আমরাই গুলিয়ে ফেলছি!”'}]},
 {key:'jealous',name:'ওই মেয়েটা কে?',story:'বর অন্য মেয়ের সঙ্গে কথা বলেছে দেখে বউ রেগেছে। শান্তভাবে পরিচয় ও প্রসঙ্গ বলুন, তারপর একসঙ্গে সময় দিন।',line:'বউ: “এত হাসাহাসি হচ্ছিল কার সাথে?”',steps:[{prompt:'বউ জানতে চাইছে, কার সঙ্গে কথা হচ্ছিল?',choices:[['explain','দর্জি আপা—তোমার শাড়ির মাপ নিয়ে কথা'],['dismiss','তোমার জানার দরকার নেই'],['tease','রাগলে তোমাকে ভালো লাগে!']],correct:'explain',reply:'বর: “উনি দর্জি আপা। ব্লাউজ কবে হবে, সেটাই জিজ্ঞেস করছিলাম।”'},{prompt:'পরিচয় পরিষ্কার, কিন্তু মন খারাপ রয়ে গেছে।',choices:[['listen','কেন খারাপ লেগেছে, বলো—শুনছি'],['phone','ফোন দেখিয়ে তর্ক করি'],['walk','চলে যাই']],correct:'listen',reply:'বউ: “আগে পরিচয় করিয়ে দিলে ভুল বুঝতাম না।”'},{prompt:'এবার কী করবেন?',choices:[['time','চলো একসঙ্গে শাড়িটা নিয়ে আসি'],['joke','আরেকটু খেপাই']],correct:'time',reply:'বউ: “ঠিক আছে। ফেরার পথে জিলাপি কিন্তু চাই!”'}]},
 {key:'phone',name:'ফোনের সাথে সংসার?',story:'ফোন সরিয়ে বউয়ের কথা আট সেকেন্ড মন দিয়ে শুনুন। মাঝখানে ফোন ধরলে আবার শুরু!',line:'বউ: “তোমার সংসার কি ফোনের সাথে?”'},
 {key:'market',name:'ফুল দিয়ে তরকারি হয়?',story:'ধনেপাতা ভুলে গেলে আগে সেটা আনতে হবে। ফুল দিয়ে আসল কাজ এড়ালে অভিমান বাড়বে।',line:'বউ: “রান্না আটকে আছে, আর তুমি ফুল আনছো?”',steps:[{prompt:'তরকারিতে ধনেপাতা নেই। কী আনবেন?',choices:[['flower','এক তোড়া ফুল'],['coriander','বাজার থেকে ধনেপাতা'],['excuse','কাল আনব বলি']],correct:'coriander',reply:'বউ: “এই তো! এবার রান্নাটা শেষ করা যাবে।”'},{prompt:'ভুলটা কীভাবে শুধরাবেন?',choices:[['sorry','ভুল হয়েছে, পরেরবার তালিকা মিলাব'],['blame','তুমি মনে করিয়ে দাওনি!']],correct:'sorry',reply:'বর: “তালিকা লিখেছি। এবার টিক দিয়েই বাজার করব!”'},{prompt:'রান্না শেষ করতে সাহায্য করুন।',choices:[['help','ধনেপাতা ধুয়ে কেটে দিই'],['rest','আমি একটু ঘুমাই']],correct:'help',reply:'বউ: “ফুলটা এখন দাও, এবার ভালো লাগবে!”'}]},
 {key:'birthday',name:'জন্মদিন ভুলে গেছো!',story:'প্রথমে সত্যি করে সরি বলুন, তারপর কেক আনুন। শেষে ফোন সরিয়ে আট সেকেন্ড একসঙ্গে সময় কাটান।',line:'বউ: “আজ কী দিন, মনে আছে?”',steps:[{prompt:'জন্মদিনের কথা ভুলে গেছেন।',choices:[['sorry','সরি, ভুলটা আমার হয়েছে'],['excuse','আমি তো সারপ্রাইজ দিচ্ছিলাম!']],correct:'sorry',reply:'বউ: “অজুহাত না দিয়ে বললে ভালো লাগে।”'},{prompt:'ছোট্ট আয়োজন করুন।',choices:[['cake','কেক ও মোমবাতি আনি'],['money','টাকা দিলেই তো হয়'],['flower','শুধু ফুল দিয়ে শেষ করি']],correct:'cake',reply:'বউ: “কেক তো হলো, এবার পাশে বসো।”'}]},
 {key:'chores',name:'আজ কাজ ভাগ করে নিই',story:'ছয়বার ঘষে বাসন পরিষ্কার করুন। তারপর চায়ে ঠিক দুই চামচ চিনি দিয়ে পরিবেশন করুন।',line:'বউ: “আজ বাসন আর চা তুমি করো, আমি একটু বসি।”'}
].map(x=>({...x,role:'husband',type:'mend',shots:0}));
function render(g,d){const m=g.mending;if(!m)return;$('anger').value=m.anger;$('anger-text').textContent='অভিমান '+m.anger+'%';$('mend-progress').textContent=m.message||d.story;const buttons=$('mend-actions');buttons.replaceChildren();const add=(id,label,disabled=false)=>{const b=document.createElement('button');b.type='button';b.id='choice-'+id;b.textContent=label;b.disabled=disabled||g.state!=='mending';b.onclick=()=>window.AngryBouMend.choose(id);buttons.appendChild(b);};
 if(d.key==='chores'){if(m.stage===0){$('mend-prompt').textContent='বাসন পরিষ্কার: '+m.scrubs+' / ৬ বার';add('scrub','🧽 বাসন ঘষুন');}else{$('mend-prompt').textContent='চিনি: '+m.sugar+' চামচ · ঠিক ২ চামচ চাই';add('sugar','🥄 এক চামচ চিনি',m.sugar>=4);add('serve','☕ চা পরিবেশন');add('newtea','নতুন চা বানাই');}}
 else if(d.key==='phone'||(d.key==='birthday'&&m.stage>=2)){$('mend-prompt').textContent=m.listening?'কথা শুনছেন… '+Math.floor(m.listenTime)+' / ৮ সেকেন্ড':'ফোন সরিয়ে মন দিয়ে কথা শুনুন';add('listen','♡ ফোন সরিয়ে কথা শুনি',m.listening);add('phone','📱 একবার ফোনটা দেখি');}
 else{const step=d.steps[m.stage];$('mend-prompt').textContent=step?step.prompt:'মান ভেঙেছে!';if(step)step.choices.forEach(([id,label])=>add(id,label));}
}
let hooks=null,current=null;
function start(g,d,h){hooks=h;current={g,d};g.mending={anger:90,stage:0,scrubs:0,sugar:0,listening:false,listenTime:0,actions:0,message:d.line};g.state='mending';render(g,d);}
function choose(id){if(!current)return;const {g,d}=current,m=g.mending;if(g.state!=='mending')return;m.actions++;g.shotCount=m.actions;
 const wrong=text=>{m.anger=Math.min(100,m.anger+12);g.scratch=3;m.message=text;hooks.say(text,text);hooks.tone(150);render(g,d);};
 const progress=(text,amount=28)=>{m.anger=Math.max(5,m.anger-amount);g.score+=200;g.wifeDance=.7;m.message=text;hooks.say(text);hooks.tone(600);};
 const win=()=>{m.anger=0;g.score+=600;m.message='কাজে আর কথায় মান ভাঙল!';render(g,d);hooks.win();};
 if(d.key==='chores'){if(m.stage===0&&id==='scrub'){m.scrubs++;progress('বর: “বাসনও চকচক, সংসারও ঝকঝক!”',6);if(m.scrubs===6){m.stage=1;m.message='বাসন পরিষ্কার! এবার চায়ে ঠিক দুই চামচ চিনি দিন।';}}else if(m.stage===1){if(id==='sugar'&&m.sugar<4)m.sugar++;else if(id==='newtea'){m.sugar=0;m.message='নতুন কাপ তৈরি। এবার মেপে চিনি দিন।';}else if(id==='serve'){if(m.sugar===2){win();return;}wrong(m.sugar>2?'বউ: “চা বানাইছো, না চিনির শরবত?”':'বউ: “চিনিটা একটু কম হয়ে গেছে!”');m.sugar=0;}}}
 else if(d.key==='phone'||(d.key==='birthday'&&m.stage>=2)){if(id==='listen'){m.listening=true;m.listenTime=0;m.listenStart=m.anger;m.message='বউ: “আজকের সারাদিনের গল্পটা বলি… তুমি শুনো।”';hooks.say(m.message);}else if(id==='phone'){m.listening=false;m.listenTime=0;wrong('বউ: “তোমার সংসার কি ফোনের সাথে?”');return;}}
 else{const step=d.steps[m.stage];if(!step||!step.choices.some(c=>c[0]===id))return;if(id!==step.correct){wrong(d.key==='market'&&id==='flower'?'বউ: “ফুল দিয়ে কি তরকারি রান্না করমু?”':'বউ: “আমার কথাটা আগে বুঝে শোনো!”');return;}progress(step.reply);m.stage++;if(m.stage===d.steps.length&&d.key!=='birthday'){win();return;}}
 hooks.hud();render(g,d);
}
function tick(g,d,dt){const m=g.mending;if(!m||!m.listening||g.state!=='mending')return;const before=Math.floor(m.listenTime);m.listenTime+=dt;m.anger=Math.max(0,Math.round((m.listenStart||90)*(1-m.listenTime/8)));$('anger').value=m.anger;$('anger-text').textContent='অভিমান '+m.anger+'%';if(Math.floor(m.listenTime)!==before)$('mend-prompt').textContent='কথা শুনছেন… '+Math.min(8,Math.floor(m.listenTime))+' / ৮ সেকেন্ড';if(m.listenTime>=8){m.listening=false;m.anger=0;g.score+=1000;m.message='বউ: “এভাবে পাশে থাকলেই তো ভালো লাগে!”';render(g,d);hooks.win();}}
window.AngryBouMend={chapters,start,choose,tick,render};
})();

