'use strict';
(() => {
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d');
const levels=[
 {name:'ধনেপাতা গেল কই?',role:'wife',type:'break',shots:5,items:['ভুল তালিকা','অজুহাত','ভুলোমন'],story:'বর সব এনেছে… ধনেপাতা ছাড়া! বউ হয়ে অজুহাতের টাওয়ার ভাঙুন।',line:'বর: “ধনেপাতাও কি আলাদা করে কিনতে হয়?”'},
 {name:'ফুল দিয়ে মান ভাঙাই',role:'husband',type:'deliver',shots:5,want:'flower',story:'বরের পালা: ফুল বেছে বউয়ের ঝুড়িতে পৌঁছে দিন। কাছে গিয়ে আবার ট্যাপ করলে ধীরে নামবে।',line:'বউ: “ফুল আনছো ভালো, কাল ধনেপাতাও আনবা!”'},
 {name:'বিয়েবাড়ির সেলফি',role:'wife',type:'break',shots:5,items:['লজ্জা','ঝাপসা ছবি','বন্ধ ক্যামেরা','অজুহাত'],story:'বিয়েবাড়িতে বর ছবি তুলতে চায় না! বউ হয়ে সেলফির সব বাধা সরান।',line:'বর: “একটা ছবি বলছিলা, এইটা তো আটচল্লিশ নম্বর!”'},
 {name:'গরম জিলাপির সন্ধি',role:'husband',type:'deliver',shots:5,want:'jalebi',moving:true,story:'বরের পালা: জিলাপি বাছুন, চলন্ত ঝুড়িতে পৌঁছান। ভুল খাবারে অভিমান ভাঙবে না!',line:'বউ: “মিষ্টি কথা না, গরম জিলাপি চাই!”'},
 {name:'চায়ে চিনি বেশি!',role:'wife',type:'break',shots:5,items:['চিনির পাহাড়','ভুল চামচ','বাড়তি চিনি','মিষ্টি অজুহাত'],story:'চায়ের বদলে শরবত! বউ হয়ে বাড়তি চিনির টাওয়ার ভেঙে চা ঠিক করুন।',line:'বর: “ভালোবাসা বেশি, তাই চিনিও একটু বেশি!”'},
 {name:'চুড়ি বলছি, মুড়ি না!',role:'husband',type:'deliver',shots:5,want:'bangle',story:'বরের পালা: রঙিন চুড়ি বেছে ঝুড়িতে পৌঁছান। ঝালমুড়ি দিলে কিন্তু আবার অভিমান!',line:'বর: “দোকানদারও মনে হয় মুড়ি শুনছিল!”'},
 {name:'মেলায় যাওয়ার কথা ছিল!',role:'wife',type:'break',shots:6,items:['ঘুম','কাজের অজুহাত','হারানো চাবি','দেরি','ভুল তারিখ'],story:'মেলার কথা ভুলেছে বর। বউ হয়ে সব অজুহাত সরিয়ে মেলার পথ খুলুন।',line:'বর: “মেলা কি আজকেই শেষ? আচ্ছা আচ্ছা, যাই!”'},
 {name:'দুজনের মেলা',role:'both',type:'fair',shots:7,story:'তিনটি সোনালি চুড়ি সংগ্রহ করুন। সব পেলে বর-বউ হাত ধরে মেলায় ঢুকবে!',line:'বউ: “আজ আর অভিমান না—নাগরদোলায় উঠি!”'}
];
levels.splice(7,0,...window.AngryBouMend.chapters);
const gifts={flower:'ফুল',jalebi:'জিলাপি',bangle:'চুড়ি',muri:'ঝালমুড়ি'};
const g={W:1200,H:600,ground:510,anchor:{x:210,y:363},level:0,score:0,total:0,best:0,state:'ready',shots:0,shotCount:0,combo:0,maxCombo:0,power:'mega',usedPower:false,selected:'flower',ball:null,drag:null,targets:[],blocks:[],particles:[],floats:[],rings:[],trail:[],clock:0,shake:0,chickenPanic:0,wifeDance:0,scratch:0,parade:0,elapsed:0,settle:0,winDelay:0,bonus:null,balloons:[],aim:{angle:.55,power:75},sound:false,voiceEnabled:true,voice:null};
g.mending=null;g.talkTime=0;g.speaker='wife';
let last=0,audio=null,activePointer=null,voiceTimer=null,utterance=null;
const bn=n=>String(n).replace(/\d/g,d=>'০১২৩৪৫৬৭৮৯'[d]),pick=a=>a[Math.floor(Math.random()*a.length)],info=()=>levels[g.level];
try{g.best=Number(localStorage.getItem('angry-bou-village-best'))||0;}catch{}
function tone(freq,duration=.12){if(!g.sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),v=audio.createGain();o.connect(v);v.connect(audio.destination);o.frequency.value=freq;v.gain.setValueAtTime(.065,audio.currentTime);v.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.start();o.stop(audio.currentTime+duration);}catch{}}
function cancelVoice(){clearTimeout(voiceTimer);if('speechSynthesis' in window)window.speechSynthesis.cancel();utterance=null;}
function updateVoices(){if('speechSynthesis' in window)g.voice=window.speechSynthesis.getVoices().find(v=>/^bn(?:-|_|$)/i.test(v.lang))||null;$('voice-note').textContent=g.voice?'বাংলা কণ্ঠ প্রস্তুত · শব্দ চালু করলে সংলাপ শুনবেন':'এই ব্রাউজারে বাংলা কণ্ঠ নেই—সংলাপ লেখা ও সাউন্ড ইফেক্ট থাকবে';}
function speak(text){if(!g.sound||!g.voiceEnabled||!g.voice)return;clearTimeout(voiceTimer);voiceTimer=setTimeout(()=>{if(!g.sound||!g.voiceEnabled)return;window.speechSynthesis.cancel();utterance=new SpeechSynthesisUtterance(text);utterance.voice=g.voice;utterance.lang=g.voice.lang;utterance.rate=1.02;utterance.pitch=1.08;window.speechSynthesis.speak(utterance);},100);}
function say(text,voiceText){g.talkTime=3.2;g.speaker=text.startsWith('বর:')?'husband':'wife';$('reaction').textContent=text;if(voiceText)speak(voiceText);}
function puff(x,y,color,n=15){for(let i=0;i<n;i++)g.particles.push({x,y,vx:(Math.random()-.5)*280,vy:-Math.random()*260,life:.8+Math.random()*.4,color});}
function floatText(x,y,text,color='#fff0bd'){g.floats.push({x,y,text,color,life:1.7});}
function remaining(){return g.targets.filter(t=>!t.dead).length;}
function hud(){const d=info(),delivery=d.type==='deliver';$('level').textContent=bn(g.level+1)+' / '+bn(levels.length);$('score').textContent=bn(g.total+g.score);$('best').textContent=bn(g.best);$('shots').textContent=bn(g.shots);$('targets').textContent=delivery?(remaining()?'পৌঁছায়নি':'পৌঁছেছে'):d.type==='fair'?bn(3-remaining())+' / ৩':bn(remaining());$('target-label').textContent=delivery?'গিফট':d.type==='fair'?'চুড়ি সংগৃহীত':'বাকি বাধা';$('role').textContent=d.role==='wife'?'বউয়ের পালা':d.role==='husband'?'বরের পালা':'দুজনের পালা';$('mission').textContent=d.story;$('power-select').hidden=delivery;$('gift-select').hidden=!delivery;const ready=g.state==='ready',can=g.state==='flying'&&g.ball&&!g.usedPower;$('ability').disabled=!can;$('ability').textContent=can?(delivery?'🪂 আস্তে নামাও [Space]':g.power==='mega'?'💥 এখন ফাটান! [Space]':'⚡ এখন ছুটুন! [Space]'):g.state==='flying'?'শক্তি ব্যবহার হয়েছে':'আগে শট ছুড়ুন';
 for(const mode of ['mega','turbo']){$(mode).disabled=!ready;$(mode).classList.toggle('selected',g.power===mode);$(mode).setAttribute('aria-pressed',String(g.power===mode));}
 for(const kind of Object.keys(gifts)){const b=$('gift-'+kind);b.disabled=!ready;b.classList.toggle('selected',g.selected===kind);b.setAttribute('aria-pressed',String(g.selected===kind));}$('level-select').value=String(g.level);$('mend-panel').hidden=d.type!=='mend';$('power-bar').hidden=d.type==='mend';$('shots-label').textContent=d.type==='mend'?'কাজ / কথা':'বাকি শট';if(d.type==='mend'){$('shots').textContent=bn(g.mending?.actions||0);$('targets').textContent=g.state==='won'?'খুশি':'মান ভাঙান';$('target-label').textContent='মিশন';}
}
function reset(){cancelVoice();g.mending=null;const d=info();Object.assign(g,{score:0,shots:d.shots,shotCount:0,combo:0,maxCombo:0,clock:0,shake:0,chickenPanic:0,wifeDance:0,scratch:0,parade:0,elapsed:0,settle:0,winDelay:0,ball:null,drag:null,state:'ready',usedPower:false,selected:'flower',targets:[],blocks:[],particles:[],floats:[],rings:[],trail:[],balloons:[],bonus:null});activePointer=null;$('overlay').hidden=true;$('title').textContent=d.name;$('quote').textContent=d.line;$('banter').textContent=d.story;say(d.line);
 if(d.type==='mend'){window.AngryBouMend.start(g,d,{say,tone,hud,win:celebrate});hud();return;}
 if(d.type==='break'){const cols=Math.ceil(d.items.length/2),base=770-(cols-2)*30,spacing=118+g.level*5;d.items.forEach((label,i)=>g.targets.push({x:base+(i%cols)*spacing,y:g.ground-29-Math.floor(i/cols)*116,r:28,label,dead:false}));for(let i=0;i<cols;i++){const x=base+i*spacing;g.blocks.push({x:x-49,y:417,w:17,h:93,dead:false},{x:x+32,y:417,w:17,h:93,dead:false},{x:x-54,y:394,w:108,h:20,dead:false});}g.bonus={x:610,y:210,r:24,dead:false};}
 else if(d.type==='deliver')g.targets=[{x:895,y:439,r:47,label:gifts[d.want],dead:false,baseX:895}];
 else{g.targets=[{x:760,y:300,r:28,baseX:760,baseY:300,dead:false},{x:910,y:380,r:28,baseX:910,baseY:380,dead:false},{x:1040,y:280,r:28,baseX:1040,baseY:280,dead:false}];g.balloons=[{x:560,y:210,dead:false},{x:660,y:160,dead:false},{x:1080,y:155,dead:false}];}hud();
}
function breakBlock(b){if(b.dead)return;b.dead=true;g.score+=75;puff(b.x+b.w/2,b.y+b.h/2,'#c67b49',8);}
function hitTarget(t){if(t.dead)return;t.dead=true;g.combo++;g.maxCombo=Math.max(g.maxCombo,g.combo);const points=500+Math.min(g.combo-1,5)*200;g.score+=points;puff(t.x,t.y,'#ffc85b',22);floatText(t.x,t.y-36,'+'+bn(points));g.shake=Math.max(g.shake,g.combo>1?6:3);if(info().type==='fair'){g.wifeDance=2;say('বউ: “আর '+bn(remaining())+'টা চুড়ি, তারপর নাগরদোলা!”');}else if(g.combo>1){floatText(600,150,bn(g.combo)+'× কম্বো!','#ff965f');say(pick(['বর: “ওরে বাবা! সব অজুহাত শেষ!”','পাশের বাড়ি: “পপকর্ন নিয়ে আসি?”']),'ওরে বাবা!');}else say(pick(['বর: “এইবার ঠিক জায়গায় লাগছে!”','বউ: “অজুহাত আর চলবে না!”']));tone(400+g.combo*95);hud();}
function collectBonus(){if(!g.bonus||g.bonus.dead)return;g.bonus.dead=true;g.shots++;g.score+=300;puff(g.bonus.x,g.bonus.y,'#ffe777',25);floatText(g.bonus.x,g.bonus.y-35,'+১ শট! +৩০০','#ffea78');say('বর: “ক্যাশব্যাক! আরেকটা সুযোগ!”');tone(950,.2);hud();}
function activate(){if(g.state!=='flying'||!g.ball||g.usedPower)return false;g.usedPower=true;const b=g.ball;if(info().type==='deliver'){b.vx*=.18;b.vy=40;b.parachute=true;floatText(b.x,b.y-45,'আস্তে আস্তে!','#bcefff');say('বর: “সাবধানে, গিফট আসতেছে!”');tone(600);}else if(g.power==='mega'){const {x,y}=b,r=145;g.rings.push({x,y,r,life:.55});g.shake=12;puff(x,y,'#ffb56b',40);for(const t of g.targets)if(!t.dead&&Math.hypot(t.x-x,t.y-y)<r+t.r)hitTarget(t);for(const block of g.blocks){const nx=Math.max(block.x,Math.min(x,block.x+block.w)),ny=Math.max(block.y,Math.min(y,block.y+block.h));if(Math.hypot(nx-x,ny-y)<r)breakBlock(block);}if(g.bonus&&!g.bonus.dead&&Math.hypot(g.bonus.x-x,g.bonus.y-y)<r+24)collectBonus();for(const p of g.balloons)if(!p.dead&&Math.hypot(p.x-x,p.y-y)<r+24){p.dead=true;g.score+=100;puff(p.x,p.y,'#ec84a8');}floatText(x,y-50,'মেগা অভিমান!','#fff');say('বউ: “আমি দেখেই তোমার সংসার করছি!”');b.vx*=.7;b.vy=-100;tone(100,.4);}else{b.vx=Math.max(650,Math.abs(b.vx)*1.7);b.vy=-55;b.boost=.85;floatText(b.x,b.y-45,'ঝড়ের বেগ!','#bcefff');tone(800,.2);}hud();return true;}
function launch(p){if(g.state!=='ready'||g.shots<=0)return;const dx=g.anchor.x-p.x,dy=g.anchor.y-p.y;if(Math.hypot(dx,dy)<8){g.drag=null;return;}g.shots--;g.shotCount++;g.combo=0;g.usedPower=false;g.trail=[];g.ball={x:p.x,y:p.y,vx:dx*8,vy:dy*8,r:22,kind:info().type==='deliver'?g.selected:'heart'};g.state='flying';g.elapsed=0;g.settle=0;g.drag=null;say(info().role==='husband'?'বর: “এই নাও, যত্ন করে এনেছি!”':pick(['বউ: “এই নাও ছোট্ট অভিমান!”','বর: “আলোচনা কি বসে করা যায় না?”']));tone(220,.15);hud();}
function miss(wrong=false){g.chickenPanic=3.8;g.scratch=3.5;if(!wrong)say(pick(['বউ: “এইডা কী করলা!”','বর: “এইটা ছিল ওয়ার্ম-আপ!”']),'এইডা কী করলা!');g.ball=null;g.state='settling';g.settle=0;hud();}
function deliver(t,b){if(b.kind===info().want){t.dead=true;g.combo=1;g.maxCombo=Math.max(1,g.maxCombo);g.score+=1000;g.wifeDance=4;puff(t.x,t.y,'#ef98bb',30);floatText(t.x,t.y-60,'মান ভাঙল! +১০০০');say('বউ: “আচ্ছা, এইবার মাফ করলাম!”','আচ্ছা, এইবার মাফ করলাম!');g.ball=null;tone(850,.2);}else{g.scratch=4;const text=info().want==='bangle'&&b.kind==='muri'?'আমি চুড়ি বলছি, মুড়ি না!':'আমি '+gifts[info().want]+' চাইছি, '+gifts[b.kind]+' না!';say('বউ: “'+text+'”',text);floatText(t.x,t.y-65,'ভুল গিফট!','#ffb0ac');miss(true);}hud();}
function celebrate(){g.state='celebrating';g.ball=null;g.winDelay=info().type==='fair'?8:2.4;g.parade=0;g.wifeDance=g.winDelay+1;for(let x=150;x<1100;x+=130)puff(x,120,['#ffe375','#ed887e','#a5b9ed'][Math.floor(x/130)%3],15);say(info().type==='fair'?'দুজন: “তিনটা চুড়ি পেয়েছি! চলো মেলায়!”':'বউ: “আচ্ছা, এইবার মাফ করলাম!”','আচ্ছা, এইবার মাফ করলাম!');hud();}
function finish(win){if(g.state==='won'||g.state==='lost')return;g.state=win?'won':'lost';if(info().type==='mend')window.AngryBouMend.render(g,info());if(win)g.score+=g.shots*150;const current=g.total+g.score;if(current>g.best){g.best=current;try{localStorage.setItem('angry-bou-village-best',g.best);}catch{}}hud();const stars=win?(g.shotCount<=2?3:g.shotCount<=4?2:1):0;$('stars').textContent='★'.repeat(stars)+'☆'.repeat(3-stars);$('stars').setAttribute('aria-label',bn(stars)+' / ৩ তারকা');$('resultIcon').textContent=win?'🎉':'☕';$('resultTitle').textContent=win?(info().type==='fair'?'হাত ধরে মেলায়!':info().type==='deliver'?'গিফট পেয়ে মন ভালো!':'অভিমান শেষ, হাসি শুরু!'):'চা খেয়ে আবার চেষ্টা!';$('resultText').textContent=win?'স্কোর '+bn(current)+(info().type==='mend'?' · কাজ আর কথায় অভিমান শূন্য!':' · '+bn(g.shotCount)+' শট · সেরা কম্বো '+bn(g.maxCombo)+'×'):info().type==='deliver'?'ঠিক গিফট বাছুন। ঝুড়ির কাছে গিয়ে আবার ট্যাপ করলে ধীরে নামবে।':'টাওয়ারের গোড়ায় নিশানা করুন। কাছে গিয়ে আবার ট্যাপ করলে মেগা অভিমান!';$('continue').textContent=win?(g.level===levels.length-1?'গল্প আবার শুরু ↻':'পরের পর্ব →'):'আবার চেষ্টা ↻';$('retry').hidden=!win;$('overlay').hidden=false;tone(win?780:160,.3);}
function step(dt){g.clock+=dt;g.talkTime=Math.max(0,g.talkTime-dt);for(const key of ['chickenPanic','wifeDance','scratch'])g[key]=Math.max(0,g[key]-dt);g.shake=Math.max(0,g.shake-dt*20);for(const f of g.floats){f.life-=dt;f.y-=dt*25;}g.floats=g.floats.filter(f=>f.life>0);for(const r of g.rings)r.life-=dt;g.rings=g.rings.filter(r=>r.life>0);for(const t of g.trail)t.life-=dt;g.trail=g.trail.filter(t=>t.life>0);for(const p of g.particles){p.life-=dt;p.vy+=600*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;}g.particles=g.particles.filter(p=>p.life>0);
 const d=info();if(g.bonus&&!g.bonus.dead){g.bonus.x=610+Math.sin(g.clock*1.15)*95;g.bonus.y=210+Math.sin(g.clock*1.9)*32;}if(d.type==='deliver'&&d.moving)g.targets[0].x=895+Math.sin(g.clock*.8)*50;if(d.type==='fair')g.targets.forEach((t,i)=>{t.x=t.baseX+Math.sin(g.clock*.8+i)*18;t.y=t.baseY+Math.sin(g.clock+i)*20;});
 if(g.state==='celebrating'){g.winDelay-=dt;if(d.type==='fair')g.parade=Math.min(1,g.parade+dt/4.3);if(g.winDelay<=0)finish(true);return;}if(g.state==='mending'){window.AngryBouMend.tick(g,d,dt);return;}if(g.state!=='flying'&&g.state!=='settling')return;
 if(g.ball){const b=g.ball;g.elapsed+=dt;if(!g.trail.length||Math.hypot(b.x-g.trail[g.trail.length-1].x,b.y-g.trail[g.trail.length-1].y)>10)g.trail.push({x:b.x,y:b.y,life:.35});b.boost=Math.max(0,(b.boost||0)-dt);b.vy+=(b.parachute?100:b.boost?90:520)*dt;if(b.parachute)b.vy=Math.min(150,b.vy);b.x+=b.vx*dt;b.y+=b.vy*dt;
 if(d.type==='deliver'){const t=g.targets[0];if(Math.abs(b.x-t.x)<t.r+b.r*.5&&Math.abs(b.y-t.y)<30+b.r)deliver(t,b);}else{if(g.bonus&&!g.bonus.dead&&Math.hypot(b.x-g.bonus.x,b.y-g.bonus.y)<b.r+24)collectBonus();for(const t of g.targets)if(!t.dead&&Math.hypot(b.x-t.x,b.y-t.y)<b.r+t.r){hitTarget(t);b.vx*=.83;b.vy-=50;}for(const block of g.blocks)if(!block.dead&&b.x+b.r>block.x&&b.x-b.r<block.x+block.w&&b.y+b.r>block.y&&b.y-b.r<block.y+block.h){breakBlock(block);b.vx*=b.boost?.98:.82;b.vy*=.85;tone(300,.06);hud();}for(const p of g.balloons)if(!p.dead&&Math.hypot(p.x-b.x,p.y-b.y)<b.r+23){p.dead=true;g.score+=100;puff(p.x,p.y,'#ec84a8');floatText(p.x,p.y,'+১০০');hud();}}
 if(g.ball){if(b.y+b.r>g.ground){b.y=g.ground-b.r;if(d.type==='deliver')miss();else if(Math.abs(b.vy)>65){b.vy=-Math.abs(b.vy)*.42;b.vx*=.78;tone(130,.05);}else{b.vy=0;b.vx*=Math.pow(.15,dt);}}if(g.ball&&(b.x>1280||b.x<-100||b.y>700||g.elapsed>6||(g.elapsed>1&&Math.abs(b.vx)<12&&Math.abs(b.vy)<12))){if(g.combo===0)miss();else{g.ball=null;g.state='settling';g.settle=0;hud();}}}}
 let falling=false;if(d.type==='break'){for(const b of g.blocks)if(!b.dead&&b.w>b.h){const supported=g.blocks.some(s=>!s.dead&&s.h>s.w&&Math.abs(s.y-(b.y+b.h))<4&&s.x<b.x+b.w&&s.x+s.w>b.x);if(!supported){breakBlock(b);hud();}}for(const t of g.targets)if(!t.dead){let floor=g.ground-t.r;for(const b of g.blocks)if(!b.dead&&b.w>b.h&&t.x+t.r>b.x&&t.x-t.r<b.x+b.w&&t.y+t.r<=b.y+10)floor=Math.min(floor,b.y-t.r);if(t.y<floor-1){falling=true;t.vy=(t.vy||0)+520*dt;t.y+=t.vy*dt;if(t.y>=floor){t.y=floor;if(t.vy>150){hitTarget(t);for(const other of g.targets)if(!other.dead&&other!==t&&Math.hypot(t.x-other.x,t.y-other.y)<65)hitTarget(other);}t.vy=0;}}}}
 if(remaining()===0){celebrate();return;}if(g.state==='settling'){g.settle+=dt;if(!falling&&g.settle>.45){if(g.shots<=0)finish(false);else{g.state='ready';hud();}}}
}
function position(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*1200/r.width,y:(e.clientY-r.top)*600/r.height};}
function clamp(p){let dx=p.x-g.anchor.x,dy=p.y-g.anchor.y;const d=Math.hypot(dx,dy);if(d>110){dx*=110/d;dy*=110/d;}return{x:g.anchor.x+Math.min(25,dx),y:g.anchor.y+dy};}
canvas.addEventListener('pointerdown',e=>{if(info().type==='mend')return;if(g.state==='flying'){activate();e.preventDefault();return;}if(g.state!=='ready'||activePointer!==null)return;const p=position(e);if(Math.hypot(p.x-g.anchor.x,p.y-g.anchor.y)>85)return;activePointer=e.pointerId;canvas.setPointerCapture(e.pointerId);g.drag=clamp(p);canvas.focus();e.preventDefault();});canvas.addEventListener('pointermove',e=>{if(activePointer===e.pointerId&&g.drag)g.drag=clamp(position(e));});canvas.addEventListener('pointerup',e=>{if(activePointer!==e.pointerId)return;activePointer=null;if(g.drag)launch(g.drag);});canvas.addEventListener('pointercancel',()=>{activePointer=null;g.drag=null;});
function adjust(code){if(code==='ArrowLeft')g.aim.angle=Math.min(1.35,g.aim.angle+.05);if(code==='ArrowRight')g.aim.angle=Math.max(.1,g.aim.angle-.05);if(code==='ArrowUp')g.aim.power=Math.min(110,g.aim.power+5);if(code==='ArrowDown')g.aim.power=Math.max(25,g.aim.power-5);g.drag={x:g.anchor.x-Math.cos(g.aim.angle)*g.aim.power,y:g.anchor.y+Math.sin(g.aim.angle)*g.aim.power};}
canvas.addEventListener('keydown',e=>{if(e.code==='KeyR'){reset();return;}if(info().type==='mend')return;if(e.code==='Space'){e.preventDefault();if(e.repeat)return;if(g.state==='flying'){activate();return;}}if(g.state!=='ready')return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Space'].includes(e.code)){e.preventDefault();adjust(e.code);if(e.code==='Space')launch(g.drag);}});
$('ability').onclick=activate;for(const mode of ['mega','turbo'])$(mode).onclick=()=>{if(g.state==='ready'){g.power=mode;hud();}};for(const kind of Object.keys(gifts))$('gift-'+kind).onclick=()=>{if(g.state==='ready'){g.selected=kind;hud();}};
$('restart').onclick=reset;$('retry').onclick=reset;$('continue').onclick=()=>{if(g.state==='won'){if(g.level===levels.length-1){g.level=0;g.total=0;}else{g.total+=g.score;g.level++;}}reset();};
$('sound').onclick=()=>{g.sound=!g.sound;$('sound').textContent='শব্দ: '+(g.sound?'চালু':'বন্ধ');$('sound').setAttribute('aria-pressed',String(g.sound));$('sound').setAttribute('aria-label',g.sound?'শব্দ বন্ধ করুন':'শব্দ চালু করুন');if(!g.sound)cancelVoice();else{updateVoices();tone(500);speak('চলো, খেলা শুরু করি!');}};$('voice').onclick=()=>{g.voiceEnabled=!g.voiceEnabled;$('voice').textContent='কথা: '+(g.voiceEnabled?'চালু':'বন্ধ');$('voice').setAttribute('aria-pressed',String(g.voiceEnabled));if(!g.voiceEnabled)cancelVoice();};
levels.forEach((d,i)=>{const o=document.createElement('option');o.value=String(i);o.textContent=bn(i+1)+'. '+d.name;$('level-select').appendChild(o);});$('level-select').onchange=()=>{g.level=Number($('level-select').value);g.total=0;reset();};if('speechSynthesis' in window)window.speechSynthesis.addEventListener('voiceschanged',updateVoices);document.addEventListener('visibilitychange',()=>{last=0;if(document.hidden)cancelVoice();});updateVoices();
function frame(ts){const dt=document.hidden?0:Math.min((ts-last)/1000||0,.05);last=ts;for(let i=0;i<4;i++)step(dt/4);window.drawAngryBou(ctx,g,info(),gifts);requestAnimationFrame(frame);}reset();requestAnimationFrame(frame);
})();
